### ISSUE TITLE
xml:id value and filename should match

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-lit#1]
Currently there are several files with the same xml:id: this is invalid: the xml:id should correspond with the LITxxxx part of the filename.

**Comment by morethanbooks** [comment]
Yes, this happens for example in file "LIT00006_kudirka_virsininkai.xml", which in the file (element TEI), has the following value: xml:id="LIT00011"

**Comment by lb42** [comment]
Our Lithuanian colleagues don't seem to be active, so I have taken the liberty of fixing all these myself.
